server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: momomo
    password: 20040813,ljh.
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr:  localhost:8848
      discovery:
        cluster-name: HZ
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice: # 给某个微服务配置负载均衡规则，这里是userservice服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    enabled: true
    clients: userservice
#feign:
#  client:
#    config:
#      default:
#        logger-level: FULL